# Generated by Django 2.2 on 2019-06-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oanda', '0004_auto_20190603_2051'),
        ('learning', '0006_learningmodel_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='OandaStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='oanda.Account')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='learning.LearningModel')),
            ],
        ),
    ]
