# Generated by Django 2.2 on 2019-07-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20190625_1536'),
        ('roboto', '0008_instrumentvalue'),
        ('oanda', '0020_auto_20190707_0908'),
        ('strategy', '0002_auto_20190706_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='oanda.Account')),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboto.Instrument')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='learning.LearningModel')),
            ],
        ),
        migrations.DeleteModel(
            name='OandaStrategy',
        ),
    ]
