# Generated by Django 2.2 on 2019-07-14 10:15

from django.db import migrations, models
import django.db.models.deletion
import strategy.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_auto_20190625_1536'),
        ('roboto', '0008_instrumentvalue'),
        ('oanda', '0020_remove_trade_strategy'),
        ('strategy', '0002_auto_20190706_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='oanda.Account')),
                ('instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roboto.Instrument')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategies', to='learning.LearningModel')),
            ],
            bases=(models.Model, strategy.models.StrategyInterface),
        ),
        migrations.CreateModel(
            name='StrategyToTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.Strategy')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oanda.Trade', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OandaStrategy',
        ),
        migrations.AddField(
            model_name='strategy',
            name='trades',
            field=models.ManyToManyField(through='strategy.StrategyToTrade', to='oanda.Trade'),
        ),
    ]
