# Generated by Django 2.2 on 2019-07-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20190714_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategytotrade',
            name='trade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oanda.Trade'),
        ),
    ]
