# Generated by Django 2.2 on 2019-07-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_auto_20190714_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='last_tick',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
