version: "3"

networks:
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.app
    env_file:
      - app.env
    depends_on:
      - mysql
    networks:
      - dev
    restart: always
    volumes:
      - .:/opt/project

  celery-worker:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.app
    env_file:
      - app.env
    depends_on:
      - mysql
      - redis
    networks:
      - dev
    restart: always
    volumes:
      - .:/opt/project
    command: celery -A roboto.celery_app worker --loglevel=info --beat

  jupyter:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.app
    env_file:
      - app.env
    depends_on:
      - mysql
    networks:
      - dev
    restart: always
    volumes:
      - .:/opt/project
      - ./deploy/jupyter/jupyter_notebook_config.json:/root/.jupyter/jupyter_notebook_config.json
    command: ./manage.py shell_plus --notebook

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: roboto
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: roboto
    networks:
      - dev
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis
    networks:
      - dev

  minio:
    image: minio/minio
    volumes:
      - minio-data:/export
    networks:
      - dev
    environment:
      MINIO_ACCESS_KEY: development_minio_key
      MINIO_SECRET_KEY: development_minio_secret
    command: server /export

  airflow-database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: roboto
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: airflow
    networks:
      - dev
    volumes:
      - airflow-mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  airflow-webserver:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.app
    environment:
      AIRFLOW_HOME: /opt/project/airflow_home
    networks:
      - dev
    volumes:
       - .:/opt/project
    command: airflow webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-database
      - redis

  airflow-scheduler:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.app
    environment:
      AIRFLOW_HOME: /opt/project/airflow_home
    networks:
      - dev
    volumes:
      - .:/opt/project
    command: airflow scheduler
    depends_on:
      - airflow-database
      - redis

  airflow-worker:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.app
    environment:
      AIRFLOW_HOME: /opt/project/airflow_home
      C_FORCE_ROOT: 1
    networks:
      - dev
    volumes:
      - .:/opt/project
    command: airflow worker
    depends_on:
      - airflow-database
      - redis
    ports:
      - "8793:8793"

  nginx:
    image: nginx
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - dev
    ports:
      - "81:80"
    depends_on:
      - jupyter
#      - app

volumes:
  mysql-data:
    driver: local
  airflow-mysql-data:
    driver: local
  jupyter-config:
    driver: local
  minio-data:
    driver: local
