version: "3"

networks:
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - app.env
    depends_on:
      - mysql
    networks:
      - dev
    ports:
      - "8001:8000"
    restart: always
    volumes:
      - .:/opt/project

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - app.env
    depends_on:
      - mysql
      - redis
    networks:
      - dev
    restart: always
    volumes:
      - .:/opt/project
    command: celery -A roboto.celery_app worker --loglevel=info --beat

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.app
    env_file:
      - app.env
    depends_on:
      - mysql
    networks:
      - dev
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - .:/opt/project
      - ./deploy/jupyter/jupyter_notebook_config.json:/root/.jupyter/jupyter_notebook_config.json
    command: ./manage.py shell_plus --notebook

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: roboto
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: roboto
    networks:
      - dev
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis
    networks:
      - dev

  minio:
    image: minio/minio
    volumes:
      - minio-data:/export
    networks:
      - dev
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: development_minio_key
      MINIO_SECRET_KEY: development_minio_secret
    command: server /export

  nginx:
    image: nginx
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - dev
    ports:
      - "80:80"
    depends_on:
      - jupyter
      - app

volumes:
  mysql-data:
    driver: local
  jupyter-config:
    driver: local
  minio-data:
    driver: local
