# Generated by Django 2.2 on 2019-07-28 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finam_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='finam_data.Instrument'),
        ),
    ]
