# Generated by Django 2.2 on 2019-07-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam_data', '0002_auto_20190728_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='close',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='high',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='low',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candle',
            name='open',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
