# Generated by Django 2.2 on 2019-08-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finam_data', '0003_auto_20190728_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='market',
            field=models.SmallIntegerField(choices=[(45, 'Moscow currencies'), (5, 'World currencies')]),
        ),
    ]
