# Generated by Django 2.2 on 2019-06-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='LearningModel',
        ),
    ]
