# Generated by Django 2.2 on 2019-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20190616_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodel',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='file',
            field=models.FileField(upload_to='learning_models/'),
        ),
    ]
