# Generated by Django 2.2 on 2019-06-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20190616_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodel',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'keras')], default=0),
            preserve_default=False,
        ),
    ]
