# Generated by Django 2.2 on 2019-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learningmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodel',
            name='features',
            field=models.TextField(blank=True),
        ),
    ]
