# Generated by Django 2.2 on 2019-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_learningmodel_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningmodel',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='learning_models/'),
            preserve_default=False,
        ),
    ]
