# Generated by Django 2.2 on 2019-06-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_auto_20190621_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningmodel',
            old_name='features',
            new_name='_features',
        ),
        migrations.AlterField(
            model_name='learningmodel',
            name='_features',
            field=models.TextField(blank=True, db_column='features'),
        ),
    ]
