# Generated by Django 2.2 on 2019-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='candle',
            name='close',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='high',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='low',
        ),
        migrations.RemoveField(
            model_name='candle',
            name='open',
        ),
        migrations.AddField(
            model_name='candle',
            name='ask_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='ask_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='ask_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='ask_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='bid_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='bid_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='bid_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='bid_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='mid_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='mid_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='mid_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candle',
            name='mid_open',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
