# Generated by Django 2.2 on 2019-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0002_auto_20190602_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candle',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
