# Generated by Django 2.2 on 2019-07-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0004_auto_20190603_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('units', models.SmallIntegerField()),
                ('pl', models.FloatField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oanda.Account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oanda.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oanda.Trade')),
            ],
        ),
    ]
