# Generated by Django 2.2 on 2019-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0006_auto_20190704_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trade',
            name='pl',
            field=models.FloatField(blank=True),
        ),
    ]
