# Generated by Django 2.2 on 2019-07-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0009_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='oanda.Trade'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'order create'), (1, 'fill')]),
        ),
    ]
