# Generated by Django 2.2 on 2019-07-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0011_transaction_external_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='time',
        ),
    ]
