# Generated by Django 2.2 on 2019-07-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0012_auto_20190704_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_closed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_opened',
            field=models.TextField(null=True),
        ),
    ]
