# Generated by Django 2.2 on 2019-07-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0013_auto_20190704_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='external_id',
            new_name='trade_id',
        ),
    ]
