# Generated by Django 2.2 on 2019-07-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0014_auto_20190704_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roboto.Instrument'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roboto.Instrument'),
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
    ]
