# Generated by Django 2.2 on 2019-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0015_auto_20190704_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
