# Generated by Django 2.2 on 2019-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0016_auto_20190704_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'init'), (1, 'open'), (2, 'close'), (3, 'cancel')], default=0),
        ),
    ]
