# Generated by Django 2.2 on 2019-07-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
        ('oanda', '0017_trade_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strategy.OandaStrategy'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'init'), (1, 'open'), (2, 'close'), (3, 'cancel'), (4, 'open error'), (5, 'close error')], default=0),
        ),
    ]
