# Generated by Django 2.2 on 2019-07-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0019_auto_20190706_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='strategy',
        ),
    ]
