# Generated by Django 2.2 on 2019-06-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboto', '0004_auto_20190603_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='value_type',
            field=models.IntegerField(choices=[(1, 'Float'), (2, 'Text')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instrument',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
