# Generated by Django 2.2 on 2019-06-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboto', '0005_auto_20190603_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='descriptions',
            new_name='description',
        ),
    ]
