# Generated by Django 2.2 on 2019-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roboto', '0006_auto_20190603_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='granularity',
            field=models.IntegerField(choices=[('1', 'S5'), ('2', 'H1')], default=2),
            preserve_default=False,
        ),
    ]
